// Code generated by MockGen. DO NOT EDIT.
// Source: repository/es_bulk_indices_repository.go

package mocks

import (
	bytes "bytes"
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBulkDocumentIndexer is a mock of BulkDocumentIndexer interface
type MockBulkDocumentIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockBulkDocumentIndexerMockRecorder
}

// MockBulkDocumentIndexerMockRecorder is the mock recorder for MockBulkDocumentIndexer
type MockBulkDocumentIndexerMockRecorder struct {
	mock *MockBulkDocumentIndexer
}

// NewMockBulkDocumentIndexer creates a new mock instance
func NewMockBulkDocumentIndexer(ctrl *gomock.Controller) *MockBulkDocumentIndexer {
	mock := &MockBulkDocumentIndexer{ctrl: ctrl}
	mock.recorder = &MockBulkDocumentIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBulkDocumentIndexer) EXPECT() *MockBulkDocumentIndexerMockRecorder {
	return _m.recorder
}

// BulkIndices mocks base method
func (_m *MockBulkDocumentIndexer) BulkIndices(ctc context.Context, buf bytes.Buffer, indexName string) error {
	ret := _m.ctrl.Call(_m, "BulkIndices", ctc, buf, indexName)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkIndices indicates an expected call of BulkIndices
func (_mr *MockBulkDocumentIndexerMockRecorder) BulkIndices(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "BulkIndices", reflect.TypeOf((*MockBulkDocumentIndexer)(nil).BulkIndices), arg0, arg1, arg2)
}
