// Code generated by MockGen. DO NOT EDIT.
// Source: error/error_response_interceptor.go

package mocks

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	."gitlab.com/spitertech/recommender/error"
	reflect "reflect"
)

// MockErrResponseInterceptor is a mock of ErrResponseInterceptor interface
type MockErrResponseInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockErrResponseInterceptorMockRecorder
}

// MockErrResponseInterceptorMockRecorder is the mock recorder for MockErrResponseInterceptor
type MockErrResponseInterceptorMockRecorder struct {
	mock *MockErrResponseInterceptor
}

// NewMockErrResponseInterceptor creates a new mock instance
func NewMockErrResponseInterceptor(ctrl *gomock.Controller) *MockErrResponseInterceptor {
	mock := &MockErrResponseInterceptor{ctrl: ctrl}
	mock.recorder = &MockErrResponseInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockErrResponseInterceptor) EXPECT() *MockErrResponseInterceptorMockRecorder {
	return _m.recorder
}

// HandleBadRequest mocks base method
func (_m *MockErrResponseInterceptor) HandleBadRequest(ctx *gin.Context, bindErr error) {
	_m.ctrl.Call(_m, "HandleBadRequest", ctx, bindErr)
}

// HandleBadRequest indicates an expected call of HandleBadRequest
func (_mr *MockErrResponseInterceptorMockRecorder) HandleBadRequest(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "HandleBadRequest", reflect.TypeOf((*MockErrResponseInterceptor)(nil).HandleBadRequest), arg0, arg1)
}

// HandleServiceError mocks base method
func (_m *MockErrResponseInterceptor) HandleServiceError(ctx *gin.Context, serviceErr *RECOMError) {
	_m.ctrl.Call(_m, "HandleServiceError", ctx, serviceErr)
}

// HandleServiceError indicates an expected call of HandleServiceError
func (_mr *MockErrResponseInterceptorMockRecorder) HandleServiceError(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "HandleServiceError", reflect.TypeOf((*MockErrResponseInterceptor)(nil).HandleServiceError), arg0, arg1)
}
