// Code generated by MockGen. DO NOT EDIT.
// Source: repository/es_indexer_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEsDocumentIndexerRepository is a mock of EsDocumentIndexerRepository interface
type MockEsDocumentIndexerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEsDocumentIndexerRepositoryMockRecorder
}

// MockEsDocumentIndexerRepositoryMockRecorder is the mock recorder for MockEsDocumentIndexerRepository
type MockEsDocumentIndexerRepositoryMockRecorder struct {
	mock *MockEsDocumentIndexerRepository
}

// NewMockEsDocumentIndexerRepository creates a new mock instance
func NewMockEsDocumentIndexerRepository(ctrl *gomock.Controller) *MockEsDocumentIndexerRepository {
	mock := &MockEsDocumentIndexerRepository{ctrl: ctrl}
	mock.recorder = &MockEsDocumentIndexerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEsDocumentIndexerRepository) EXPECT() *MockEsDocumentIndexerRepositoryMockRecorder {
	return m.recorder
}

// IndexDocument mocks base method
func (m *MockEsDocumentIndexerRepository) IndexDocument(ctx context.Context, doc interface{}) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IndexDocument", ctx, doc)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IndexDocument indicates an expected call of IndexDocument
func (mr *MockEsDocumentIndexerRepositoryMockRecorder) IndexDocument(ctx, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexDocument", reflect.TypeOf((*MockEsDocumentIndexerRepository)(nil).IndexDocument), ctx, doc)
}
