// Code generated by MockGen. DO NOT EDIT.
// Source: controller/search_controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSearchController is a mock of SearchController interface
type MockSearchController struct {
	ctrl     *gomock.Controller
	recorder *MockSearchControllerMockRecorder
}

// MockSearchControllerMockRecorder is the mock recorder for MockSearchController
type MockSearchControllerMockRecorder struct {
	mock *MockSearchController
}

// NewMockSearchController creates a new mock instance
func NewMockSearchController(ctrl *gomock.Controller) *MockSearchController {
	mock := &MockSearchController{ctrl: ctrl}
	mock.recorder = &MockSearchControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSearchController) EXPECT() *MockSearchControllerMockRecorder {
	return m.recorder
}

// Search mocks base method
func (m *MockSearchController) Search(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Search", ctx)
}

// Search indicates an expected call of Search
func (mr *MockSearchControllerMockRecorder) Search(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchController)(nil).Search), ctx)
}

// RecommendSearch mocks base method
func (m *MockSearchController) RecommendSearch(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecommendSearch", ctx)
}

// RecommendSearch indicates an expected call of RecommendSearch
func (mr *MockSearchControllerMockRecorder) RecommendSearch(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecommendSearch", reflect.TypeOf((*MockSearchController)(nil).RecommendSearch), ctx)
}
