// Code generated by MockGen. DO NOT EDIT.
// Source: error/elasticsearch_error_interceptor.go

package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	. "gitlab.com/spitertech/recommender/error"
	reflect "reflect"
)

// MockElasticSearchErrorInterceptor is a mock of ElasticSearchErrorInterceptor interface
type MockElasticSearchErrorInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSearchErrorInterceptorMockRecorder
}

// MockElasticSearchErrorInterceptorMockRecorder is the mock recorder for MockElasticSearchErrorInterceptor
type MockElasticSearchErrorInterceptorMockRecorder struct {
	mock *MockElasticSearchErrorInterceptor
}

// NewMockElasticSearchErrorInterceptor creates a new mock instance
func NewMockElasticSearchErrorInterceptor(ctrl *gomock.Controller) *MockElasticSearchErrorInterceptor {
	mock := &MockElasticSearchErrorInterceptor{ctrl: ctrl}
	mock.recorder = &MockElasticSearchErrorInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockElasticSearchErrorInterceptor) EXPECT() *MockElasticSearchErrorInterceptorMockRecorder {
	return _m.recorder
}

// ErrorMapper mocks base method
func (_m *MockElasticSearchErrorInterceptor) ErrorMapper(ctx context.Context, err error) *RECOMError {
	ret := _m.ctrl.Call(_m, "ErrorMapper", ctx, err)
	ret0, _ := ret[0].(*RECOMError)
	return ret0
}

// ErrorMapper indicates an expected call of ErrorMapper
func (_mr *MockElasticSearchErrorInterceptorMockRecorder) ErrorMapper(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ErrorMapper", reflect.TypeOf((*MockElasticSearchErrorInterceptor)(nil).ErrorMapper), arg0, arg1)
}
