// Code generated by MockGen. DO NOT EDIT.
// Source: service/es_bulk_indexer.go

package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "gitlab.com/spitertech/recommender/models"
	reflect "reflect"
)

// MockBulkIndexer is a mock of BulkIndexer interface
type MockBulkIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockBulkIndexerMockRecorder
}

// MockBulkIndexerMockRecorder is the mock recorder for MockBulkIndexer
type MockBulkIndexerMockRecorder struct {
	mock *MockBulkIndexer
}

// NewMockBulkIndexer creates a new mock instance
func NewMockBulkIndexer(ctrl *gomock.Controller) *MockBulkIndexer {
	mock := &MockBulkIndexer{ctrl: ctrl}
	mock.recorder = &MockBulkIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockBulkIndexer) EXPECT() *MockBulkIndexerMockRecorder {
	return _m.recorder
}

// ProductBulkIndexer mocks base method
func (_m *MockBulkIndexer) ProductBulkIndexer(ctx context.Context, products []models.Product) (interface{}, error) {
	ret := _m.ctrl.Call(_m, "ProductBulkIndexer", ctx, products)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProductBulkIndexer indicates an expected call of ProductBulkIndexer
func (_mr *MockBulkIndexerMockRecorder) ProductBulkIndexer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ProductBulkIndexer", reflect.TypeOf((*MockBulkIndexer)(nil).ProductBulkIndexer), arg0, arg1)
}
