// Code generated by MockGen. DO NOT EDIT.
// Source: service/es_indexer_service.go

package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	error "gitlab.com/spitertech/recommender/error"
	models "gitlab.com/spitertech/recommender/models"
	reflect "reflect"
)

// MockEsIndexerService is a mock of EsIndexerService interface
type MockEsIndexerService struct {
	ctrl     *gomock.Controller
	recorder *MockEsIndexerServiceMockRecorder
}

// MockEsIndexerServiceMockRecorder is the mock recorder for MockEsIndexerService
type MockEsIndexerServiceMockRecorder struct {
	mock *MockEsIndexerService
}

// NewMockEsIndexerService creates a new mock instance
func NewMockEsIndexerService(ctrl *gomock.Controller) *MockEsIndexerService {
	mock := &MockEsIndexerService{ctrl: ctrl}
	mock.recorder = &MockEsIndexerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockEsIndexerService) EXPECT() *MockEsIndexerServiceMockRecorder {
	return _m.recorder
}

// IndexDocuments mocks base method
func (_m *MockEsIndexerService) IndexDocuments(ctx context.Context, request models.Product) (interface{}, *error.RECOMError) {
	ret := _m.ctrl.Call(_m, "IndexDocuments", ctx, request)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(*error.RECOMError)
	return ret0, ret1
}

// IndexDocuments indicates an expected call of IndexDocuments
func (_mr *MockEsIndexerServiceMockRecorder) IndexDocuments(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "IndexDocuments", reflect.TypeOf((*MockEsIndexerService)(nil).IndexDocuments), arg0, arg1)
}
