// Code generated by MockGen. DO NOT EDIT.
// Source: repository/es_mapping_repository.go

package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockESMappingHandler is a mock of ESMappingHandler interface
type MockESMappingHandler struct {
	ctrl     *gomock.Controller
	recorder *MockESMappingHandlerMockRecorder
}

// MockESMappingHandlerMockRecorder is the mock recorder for MockESMappingHandler
type MockESMappingHandlerMockRecorder struct {
	mock *MockESMappingHandler
}

// NewMockESMappingHandler creates a new mock instance
func NewMockESMappingHandler(ctrl *gomock.Controller) *MockESMappingHandler {
	mock := &MockESMappingHandler{ctrl: ctrl}
	mock.recorder = &MockESMappingHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockESMappingHandler) EXPECT() *MockESMappingHandlerMockRecorder {
	return _m.recorder
}

// CreateMapping mocks base method
func (_m *MockESMappingHandler) CreateMapping(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "CreateMapping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMapping indicates an expected call of CreateMapping
func (_mr *MockESMappingHandlerMockRecorder) CreateMapping(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreateMapping", reflect.TypeOf((*MockESMappingHandler)(nil).CreateMapping), arg0)
}
