// Code generated by MockGen. DO NOT EDIT.
// Source: service/es_search_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	error "gitlab.com/spitertech/recommender/error"
	models "gitlab.com/spitertech/recommender/models"
	reflect "reflect"
)

// MockElasticSearchService is a mock of ElasticSearchService interface
type MockElasticSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSearchServiceMockRecorder
}

// MockElasticSearchServiceMockRecorder is the mock recorder for MockElasticSearchService
type MockElasticSearchServiceMockRecorder struct {
	mock *MockElasticSearchService
}

// NewMockElasticSearchService creates a new mock instance
func NewMockElasticSearchService(ctrl *gomock.Controller) *MockElasticSearchService {
	mock := &MockElasticSearchService{ctrl: ctrl}
	mock.recorder = &MockElasticSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockElasticSearchService) EXPECT() *MockElasticSearchServiceMockRecorder {
	return m.recorder
}

// Search mocks base method
func (m *MockElasticSearchService) Search(ctx context.Context, request models.SearchRequest) (interface{}, *error.RECOMError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, request)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(*error.RECOMError)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockElasticSearchServiceMockRecorder) Search(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockElasticSearchService)(nil).Search), ctx, request)
}

// GenerateSearchSuggestion mocks base method
func (m *MockElasticSearchService) GenerateSearchSuggestion(ctx context.Context, request models.SearchSuggestionRequest) (models.SuggestionData, *error.RECOMError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSearchSuggestion", ctx, request)
	ret0, _ := ret[0].(models.SuggestionData)
	ret1, _ := ret[1].(*error.RECOMError)
	return ret0, ret1
}

// GenerateSearchSuggestion indicates an expected call of GenerateSearchSuggestion
func (mr *MockElasticSearchServiceMockRecorder) GenerateSearchSuggestion(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSearchSuggestion", reflect.TypeOf((*MockElasticSearchService)(nil).GenerateSearchSuggestion), ctx, request)
}
