// Code generated by MockGen. DO NOT EDIT.
// Source: controller/indexer_controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIndexerController is a mock of IndexerController interface
type MockIndexerController struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerControllerMockRecorder
}

// MockIndexerControllerMockRecorder is the mock recorder for MockIndexerController
type MockIndexerControllerMockRecorder struct {
	mock *MockIndexerController
}

// NewMockIndexerController creates a new mock instance
func NewMockIndexerController(ctrl *gomock.Controller) *MockIndexerController {
	mock := &MockIndexerController{ctrl: ctrl}
	mock.recorder = &MockIndexerControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIndexerController) EXPECT() *MockIndexerControllerMockRecorder {
	return m.recorder
}

// IndexDocument mocks base method
func (m *MockIndexerController) IndexDocument(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IndexDocument", ctx)
}

// IndexDocument indicates an expected call of IndexDocument
func (mr *MockIndexerControllerMockRecorder) IndexDocument(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IndexDocument", reflect.TypeOf((*MockIndexerController)(nil).IndexDocument), ctx)
}
