// Code generated by MockGen. DO NOT EDIT.
// Source: repository/es_search_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "gitlab.com/spitertech/recommender/models"
	reflect "reflect"
)

// MockElasticSearchRepository is a mock of ElasticSearchRepository interface
type MockElasticSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockElasticSearchRepositoryMockRecorder
}

// MockElasticSearchRepositoryMockRecorder is the mock recorder for MockElasticSearchRepository
type MockElasticSearchRepositoryMockRecorder struct {
	mock *MockElasticSearchRepository
}

// NewMockElasticSearchRepository creates a new mock instance
func NewMockElasticSearchRepository(ctrl *gomock.Controller) *MockElasticSearchRepository {
	mock := &MockElasticSearchRepository{ctrl: ctrl}
	mock.recorder = &MockElasticSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockElasticSearchRepository) EXPECT() *MockElasticSearchRepositoryMockRecorder {
	return m.recorder
}

// Search mocks base method
func (m *MockElasticSearchRepository) Search(ctx context.Context, searchString string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, searchString)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockElasticSearchRepositoryMockRecorder) Search(ctx, searchString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockElasticSearchRepository)(nil).Search), ctx, searchString)
}

// SearchSuggestions mocks base method
func (m *MockElasticSearchRepository) SearchSuggestions(ctx context.Context, request models.SearchSuggestionRequest) (models.SuggestionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSuggestions", ctx, request)
	ret0, _ := ret[0].(models.SuggestionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSuggestions indicates an expected call of SearchSuggestions
func (mr *MockElasticSearchRepositoryMockRecorder) SearchSuggestions(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSuggestions", reflect.TypeOf((*MockElasticSearchRepository)(nil).SearchSuggestions), ctx, request)
}
